Reduce the prominence of the locus in snippets
The current locus is a little noisey, and detracts from the diagnostic message, which is what we want users to be focused on.

For example, before this change we rendered:
```
error: unknown builtin: `NATRAL`

   ┌── Data/Nat.fun:7:13 ───
   │
 7 │ {-# BUILTIN NATRAL Nat #-}
   │             ^^^^^^ unknown builtin
   │
   = there is a builtin with a similar name: `NATURAL`
```
…we now render the following:
```
error: unknown builtin: `NATRAL`

   ┌─ Data/Nat.fun:7:13
   │
 7 │ {-# BUILTIN NATRAL Nat #-}
   │             ^^^^^^ unknown builtin
   │
   = there is a builtin with a similar name: `NATURAL`
```